### PR TITLE
pin versions in preparation for Renovate taking over

### PR DESCRIPTION
**Pull request by RangerRick**
I've made them deliberately low so we can see if Renovate is working properly. :)

### CODE REVIEW

**Comment by LeoColomb** [comment]
I'm not sure to understand: the lock file is already pinning the chart dependencies, and the current versions are outdated anyway 😬

**Comment by RangerRick** [comment]
@LeoColomb Renovate refused to update the current values because I suspect it doesn't like the `^`-style versions. I was going to see if doing this made it run properly.

```
DEBUG: Dependency registry-1.docker.io/bitnamicharts/common has unsupported/unversioned value ^2.19.1 (versioning=docker)
DEBUG: Skipping registry-1.docker.io/bitnamicharts/common because no currentDigest or pinDigests
DEBUG: Dependency registry-1.docker.io/bitnamicharts/postgresql has unsupported/unversioned value ^13.4.6 (versioning=docker)
DEBUG: Skipping registry-1.docker.io/bitnamicharts/postgresql because no currentDigest or pinDigests
DEBUG: Dependency registry-1.docker.io/bitnamicharts/redis has unsupported/unversioned value ^18.19.4 (versioning=docker)
DEBUG: Skipping registry-1.docker.io/bitnamicharts/redis because no currentDigest or pinDigests
```

**Comment by LeoColomb** [comment]
Oh I see. I guess it does not support OCI yet. 
Because otherwise it's working very well with this pinning. 
For example on this chart: https://github.com/YOURLS/charts

**Comment by RangerRick** [comment]
Yeah if it's not gonna work I'll just close for now and we can figure it out later. Some googling makes it look like it's a thing actively being worked on on the renovate side.

**Pull request closed without merging**
