### PR TITLE
Add a schema for values validation

### PR DESCRIPTION
**Pull request by LeoColomb**
This PR adds the `values.schema.json` file.
It is the [standard schema file](https://helm.sh/docs/topics/charts/#schema-files) for values validation.

The proposed version is relatively naive, auto-generated and without further customization.

### CODE REVIEW

**Comment by LeoColomb** [comment]
Upgrade check failure is directly linked to the type change: the validation of values before upgrades is failing. https://github.com/netbox-community/netbox-chart/actions/runs/10782731200/job/29903300695?pr=334#step:7:107

In theory, this should request a major version bump.

**Review by RangerRick — APPROVED** [review]
seems OK to me, and now is the time to do it

**Comment by LeoColomb** [comment]
@RangerRick Happy to help 😁
Just so it's clear, the upgrade check will always fail because of the type change without major version bump.

**Comment by RangerRick** [comment]
Yeah, well, I was planning on merging it anyway, but i guess our permissions lockdown means I can't, lol. I'll look at it tomorrow.

**Pull request merged**
