### PR TITLE
Fix `allowedHostsIncludesPodIP`

### LINKED ISSUE #254: allowedHostsIncludesPodIP currently broken
After deploying the current helm chart, I also ran into #166 and had a deeper look at why the PodIP is missing in my allowedHosts.

There are currently two problems with `allowedHostsIncludesPodIP`. The `P` in `IP` is capitalized in values.yaml, but not in the templates. If you want to use `allowedHostsIncludesPodIp` in your values.yaml as a workaround, helm template/install fails:

```
Error: YAML parse error on netbox/templates/deployment.yaml: error converting YAML to JSON: yaml: line 96: did not find expected key
```

This is caused by incorrect indentation in the deployment template, as there is one space too many.

I create a PR straight away to fix both problems.

### PR DESCRIPTION
**Pull request by Zaunei**
Reference: 

* Closes #254

Currently, `allowedHostsIncludesPodIP ` does not work as intended due to incorrect capitalization and an indentation mistake.

### CODE REVIEW

**Review by RangerRick — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by RangerRick** [comment]
Huh, that's weird:

https://github.com/netbox-community/netbox-chart/actions/runs/9554752952/job/26336517069?pr=255#step:7:2072

I don't see how your changes could have made it not able to use `os`, I wonder if something funky happened upstream with a version update?

**Comment by jan-schnurpfeil-gcx** [comment]
The configuration.py was still missing an `import os`. I have now also tested my branch locally on a k3s cluster and Netbox is now coming up again.

**Comment by Zaunei** [comment]
The configuration.py was still missing an `import os`. I have now also tested my branch locally on a k3s cluster and Netbox is now coming up again.

**Review by LeoColomb — DISMISSED** [review]

**Review by LeoColomb — DISMISSED** [review]

**Pull request merged**
