### PR TITLE
update examples to use the NetBox 4.x plugin API

### PR DESCRIPTION
**Pull request by RangerRick**
My Python is a bit rusty, but I _think_ this will work?

### CODE REVIEW

**Comment by RangerRick** [comment]
cc @marsteel

**Comment by LeoColomb** [comment]
I'd advocate to delegate the version comparison to Helm, based on the tag. 
Could help to avoid conflict, and might help to deprecate the old part when needed.

**Comment by RangerRick** [comment]
> I'd advocate to delegate the version comparison to Helm, based on the tag. Could help to avoid conflict, and might help to deprecate the old part when needed.

I'm not entirely sure why that's any easier than just doing it in the code the same way NetBox plugins do. If this was provided in the chart, maybe, but since it's "just" in the documentation, there aren't as many levers to pull. What would doing it based on Helm look like?

**Comment by RangerRick** [comment]
Also I'm still on the fence as to whether we even want to support 3.x, or if we just want to do a clean break and only support 4.0 and up.  The _simplest_ answer is to just use the new format...

**Comment by LeoColomb** [comment]
> Also I'm still on the fence as to whether we should even support 3.x in the 5.x charts, or if we just want to do a clean break and only support 4.0 and up.  The _simplest_ answer is to just use the new format...

Ah yes, for sure! 😁 If you ask me, I'd say only support 3.x in chart 5.x, makes things clearer and easier. But that's just my opinion, decision not on me 😊

**Comment by RangerRick** [comment]
> Ah yes, for sure! 😁 If you ask me, I'd say only support 3.x in chart 5.x, makes things clearer and easier. But that's just my opinion, decision not on me 😊

Well definitely not going to support _only_ 3.x when 4.x is current. :)

But yeah, long-term if people want to use 3.x, the 4.1.1 chart is there and works fine with a non-default PostgreSQL. I've re-pushed the PR with the simple 4.x version.

**Comment by LeoColomb** [comment]
@RangerRick Oh sorry about that typo, of course I meant Netbox 4.x. I guess replying on mobile just before a flight was not the best idea for accuracy 😁

**Pull request merged**
